version: "3.8"

services:
  api:
    image: oven/bun:latest
    volumes:
      - ./:/usr/src
    ports:
      - "3000:3000"
    expose:
      - 3000
    command: 'bash -c "cd /usr/src/packages/api && bun run dev"'

  ui:
    build:
      context: .
      dockerfile: ./packages/ui/dockerfile
    depends_on:
      - api
    volumes:
      - ./:/usr/src
    ports:
      - "4200:4200"
    command: 'bash -c "bun install -g @angular/cli && cd /usr/src && bun install && cd ./packages/ui && bun run dev:docker"'
